### ISSUE TITLE
Powering CM4 on Manta M8P v2.0

### ISSUE THREAD

**Issue by tekknix** [bigtreetech/Manta-M8P#123]
Hi, 

i've a short question about powering the CM4 on the Manta M8P V2.0 via USB (I've set the USB-PowerJumper). 

With a 5v only Powersupply i can run and program the CM4 without any issues (some undervolting-Messages from the CM4 but in general it's working).

After finish, programming and setup to go live in my Printer, i've put everything underneath my Printer (Exchange my existing LDO Leviathan with Pi5) and tried again to power it up via USB. But with the Pi5 PowerSupply. Nothing happens. It seems that every Power-Supply which delivers more as 5V only will lead to no power at all. 

I've tried again 3 different PowerSupplies with PD and QD/QC and no one powers up the CM4 and Board. If i use the simple 5V-only PowerSupply it starts up.

Any thoughts on this?

Regards
MoS-tekknix

**Comment by bigtreetech** [comment]
Definitely won't work with the Pi 5 supply. That supply won't work with most things other than a Pi 5. I am not sure what negotiation they have within it but it seems as if it will only ever put out a voltage if there is a PD chip on the other end and it is set to negotiate to the voltage and power levels that the Pi 5 expects. The M8P series does not have a PD chip for negotiation (the 5V rail should never have more than 5V on it otherwise, boom) and it is not really designed to be powered primarily from the USB port. That is a convenience included for programming. It is designed to be powered from the main voltage input via a step down regulator.
