### ISSUE TITLE
DSI and CSI Connection

### ISSUE THREAD

**Issue by Alvin5311** [bigtreetech/Manta-M8P#19]
I have the CM4 (8Gb RAM, 8Gb eMMC) on my M8P board and I've connected the BTT Pi TFT50 v2.0 and the Picam 8MP v2.0 to the DSI and CSI FPC on the bottom of the board and got no display and picture. Need help to troubleshoot.

Thanks.

**Comment by Alvin5311** [comment]
Nevermind, the type B FFC ribbon cable doesn't work for the M8P board with the Pi TFT50 v2.0 display, I had to swap it with a type A ribbon cable.

**Comment by aywosh** [comment]
Hi Alvin5311, did you find a solution because you closed the issue? I have the same issue. Thanks.

**Comment by TheLexus** [comment]
@Alvin5311 Im to try to use the M8P with a DSI 5" display which worked with a pi without problems before. But im a bit lost on how to use the dsi connector on the underside of the board... I cannot get the cable in it. What do I maybe wrong? Can you give me a hint from which side the cable plugs in... I tried it from both sides but it fits only from the "outside" where the screw hole is... but the display is not recognised by linux seen from the dmesg. It even does not light up, so I guess I made something wrong.

**Comment by TheLexus** [comment]
Ok, was able to fix it up. In the end the cable connectors were problematic. be sure that you really insert them as much as possible. On the Manta the pins need to face up (so that you see the silver plates). Verify that you use a Type-B cable which has the contacts on both ends at the same side. I used the fkms overlay instead of the kms one and no additional one for the screen. But my screen isn't from waveshare, so maybe yours different.
